{
  "hash": "10de59937796c478d63e2d49b6160585",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"\"\n---\n\n\n# Genotypic diversity and Eveness\n\nThis analysis should be conducted using **R Studio software.**\n\nLoad libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcfR)\nlibrary(poppr)\nlibrary(ape)\nlibrary(RColorBrewer)\n```\n:::\n\n\nLoad data and transform\n\n\n::: {.cell}\n\n```{.r .cell-code}\nusflu.dna2 <- fasta2DNAbin(file = 'alinhamentocerto.fas')\nisolate_name <- as.character(rownames(usflu.dna2))\ngrupos <- ifelse(startsWith(isolate_name, \"UFV\"), \"Grupo1\", \"Grupo2\")\nusflu.genind <- DNAbin2genind(x = usflu.dna2, pop = grupos)\nusflu.genind\n```\n:::\n\n\nCalculating diversity and evenness (E.5)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiversity = poppr(usflu.genind)\ndiversity\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Pop  N MLG eMLG    SE    H    G lambda   E.5  Hexp   Ia rbarD         File\n1 Grupo1 27  15 15.0 0.000 2.34 6.69  0.850 0.607 0.163 28.8 0.230 usflu.genind\n2 Grupo2 32  16 14.4 0.961 2.44 8.00  0.875 0.667 0.199 48.0 0.234 usflu.genind\n3  Total 59  26 15.2 1.742 2.72 8.23  0.878 0.511 0.181 41.1 0.200 usflu.genind\n```\n\n\n:::\n:::\n\n\n👆**interpretation**: Both groups exhibit a significant variety of multilocus genotypes (MLGs), indicating high genetic diversity within their respective populations. The Shannon-Wiener (H') and Stoddart-Taylor (G) diversity indices are quite similar across the groups, suggesting a balanced distribution of MLGs. However, Group 2 stands out with a notably higher level of genetic diversity, as indicated by a greater G value.\n\nMoreover, the lambda index, which represents the probability that two randomly chosen genotypes will be different, is slightly higher in Group 2 (0.875) compared to Group 1 (0.850). This reinforces the observation that Group 2 has higher genetic diversity, reflecting greater heterogeneity in the genotypic composition of its populations.\n\nSince the sample sizes used to calculate these diversity measures differ, direct comparison is not appropriate. Therefore, I will compute the Simpson's index, which is obtained by subtracting the sum of squared genotype frequencies from one. This index estimates the probability that two randomly selected genotypes will be different, ranging from 0 (indicating no genotype differences) to 1 (indicating maximum genotype diversity).👇\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN      <- diversity$N      \nlambda <- diversity$lambda \n(N/(N - 1)) * lambda      \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8831909 0.9032258 0.8936295\n```\n\n\n:::\n:::\n\n\nWhen calculating the adjusted Simpson's index, which reflects the probability of two genotypes being different, both groups showed high values (0.88 for Group 1 and 0.90 for Group 2), indicating high genetic diversity in both populations. Therefore, while Group 2 exhibits slightly higher diversity compared to Group 1, both demonstrate substantial levels of genetic diversity. This suggests a high likelihood of randomly sampling different genotypes from the same subpopulation\n\n## Eveness\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlg.table(usflu.genind)\n```\n\n::: {.cell-output-display}\n![](diversidade_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       MLG.1 MLG.2 MLG.3 MLG.4 MLG.5 MLG.6 MLG.7 MLG.8 MLG.9 MLG.10 MLG.11\nGrupo1     0     1     1     0     0     1     0     1     2      9      1\nGrupo2     1     0     0     1     3     0     1     0     2      9      1\n       MLG.12 MLG.13 MLG.14 MLG.15 MLG.16 MLG.17 MLG.18 MLG.19 MLG.20 MLG.21\nGrupo1      0      0      1      0      0      0      0      1      1      3\nGrupo2      1      2      0      1      1      1      1      0      0      1\n       MLG.22 MLG.23 MLG.24 MLG.25 MLG.26\nGrupo1      2      0      1      1      1\nGrupo2      2      4      0      0      0\n```\n\n\n:::\n:::\n\n\nThe E.5 evenness index revealed a uniform distribution of genotypic abundances in both populations, with values close to 0.65. This suggests that the populations maintain a broad genetic diversity without any specific genotype becoming dominant. 👆\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}